"""initial schema

Revision ID: 11e359166d6b
Revises: 
Create Date: 2026-04-14 18:33:33.031135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e359166d6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_proposals_school_type', 'proposals', ['school_pseudocode', 'intervention_type'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index('ix_proposals_submitted', 'proposals', ['submitted_at'], unique=False)
    op.create_index('ix_schools_level_risk', 'schools', ['school_level', 'risk_score'], unique=False)
    op.create_index('ix_schools_risk_level', 'schools', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schools_risk_level', table_name='schools')
    op.drop_index('ix_schools_level_risk', table_name='schools')
    op.drop_index('ix_proposals_submitted', table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index('ix_proposals_school_type', table_name='proposals')
    # ### end Alembic commands ###
